services:
  - type: web
    name: kitchensync-backend
    env: docker
    plan: free
    autoDeploy: true
    region: oregon  # ou a região que preferir
    dockerfilePath: ./dockerfile   # se renomear para Dockerfile, pode remover esta linha
    healthCheckPath: /health       # ajuste se você tiver endpoint, ex: /api/health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    # Se você usa connection string/segredos, declare aqui como envVars também.
