services:
  - type: web
    name: kitchensync-backend
    runtime: dotnet
    branch: main
    rootDir: KitchenSync.Api
    buildCommand: dotnet build
    startCommand: dotnet run --urls=http://0.0.0.0:10000
    envVars:
      - key: DOTNET_VERSION
        value: 8.0.100
